coqchk -o -R theories McPTS \
McPTS.LibTactics \
McPTS.Core.Base \
McPTS.PtsSignature.Signatures \
McPTS.PtsSignature.Predicativity \
McPTS.PtsSignature.Functionality \
McPTS.PtsSignature.Decidability \
McPTS.PtsSignature \
McPTS.Core.Syntactic.Syntax \
McPTS.Core.Syntactic.System.Definitions \
McPTS.Core.Syntactic.System.Lemmas \
McPTS.Core.Syntactic.System.Tactics \
McPTS.Core.Syntactic.System \
McPTS.Core.Syntactic.CtxSub \
McPTS.Core.Syntactic.CtxEq \
McPTS.Core.Syntactic.CoreInversions \
McPTS.Core.Syntactic.Presup \
McPTS.Core.Syntactic.SystemOpt \
McPTS.Core.Syntactic.Corollaries \
McPTS.Core.Syntactic.SystemAnnotated.Definitions \
McPTS.Core.Syntactic.SystemAnnotated.Lemmas \
McPTS.Core.Syntactic.SystemAnnotated \
McPTS.Core.Semantic.Domain \
McPTS.Core.Semantic.Evaluation.Definitions \
McPTS.Core.Semantic.Evaluation.Lemmas \
McPTS.Core.Semantic.Evaluation.Tactics \
McPTS.Core.Semantic.Evaluation \
McPTS.Core.Semantic.Readback.Definitions \
McPTS.Core.Semantic.Readback.Lemmas \
McPTS.Core.Semantic.Readback \
McPTS.Core.Semantic.NbE \
McPTS.Core.Semantic.PER.Definitions \
McPTS.Core.Semantic.PER.CoreTactics \
McPTS.Core.Semantic.PER.Lemmas \
McPTS.Core.Semantic.PER \
McPTS.Core.Semantic.Realizability \
McPTS.Core.Completeness.LogicalRelation.Definitions \
McPTS.Core.Completeness.LogicalRelation.Tactics \
McPTS.Core.Completeness.LogicalRelation.Lemmas \
McPTS.Core.Completeness.LogicalRelation \
McPTS.Core.Completeness.SortCases \
McPTS.Core.Completeness.ContextCases \
McPTS.Core.Completeness.SubstitutionCases \
McPTS.Core.Completeness.TermStructureCases \
McPTS.Core.Completeness.FunctionCases \
McPTS.Core.Completeness.SubtypingCases \
McPTS.Core.Completeness.VariableCases \
McPTS.Core.Completeness.NatCases \
McPTS.Core.Completeness.FundamentalTheorem \
McPTS.Core.Completeness \
McPTS.Core.Soundness.Weakening.Definitions \
McPTS.Core.Soundness.Weakening.Lemmas \
McPTS.Core.Soundness.LogicalRelation.Definitions \
McPTS.Core.Soundness.LogicalRelation.CoreTactics \
McPTS.Core.Soundness.LogicalRelation.CoreLemmas \
McPTS.Core.Soundness.LogicalRelation.Core \
McPTS.Core.Soundness.Realizability \
McPTS.Core.Soundness.LogicalRelation.Lemmas \
McPTS.Core.Soundness.LogicalRelation \
McPTS.Core.Soundness.ContextCases \
McPTS.Core.Soundness.TermStructureCases \
McPTS.Core.Soundness.SortCases \
McPTS.Core.Soundness.SubstitutionCases \
McPTS.Core.Soundness.FunctionCases \
McPTS.Core.Soundness.NatCases \
McPTS.Core.Soundness.FundamentalTheorem \
McPTS.Core.Soundness \
McPTS.Core.Completeness.Consequences.Types \
McPTS.Core.Completeness.Consequences.Rules \
McPTS.Core.Semantic.Consequences \
McPTS.Frontend.Elaborator \
McPTS.Algorithmic.Subtyping.Definitions \
McPTS.Algorithmic.Subtyping.Lemmas \
McPTS.Algorithmic.Subtyping \
McPTS.Algorithmic.Typing.Definitions \
McPTS.Algorithmic.Typing.Lemmas \
McPTS.Algorithmic.Typing \
McPTS.Extraction.Evaluation \
McPTS.Extraction.Readback \
McPTS.Extraction.NbE \
McPTS.Extraction.PseudoMonadic \
McPTS.Extraction.Subtyping \
McPTS.Extraction.TypeCheck \
McPTS.CaseStudies.MiniML.Signature \
McPTS.CaseStudies.LF.Signature \
McPTS.CaseStudies.MLTTCumul.Signature \
McPTS.CaseStudies.MLTTNonCumul.Signature \
McPTS.CaseStudies.MLTTOmega.Signature \
McPTS.CaseStudies.STLC.Signature
