(include_subdirs no)

(library
 (name McptsLib_LF)
 (public_name mcpts.driver_lf)
 (modules Main Lexer PrettyPrinter Test)
 (libraries McptsExtracted_LF)
 (inline_tests
  (deps
   (glob_files_rec ../examples/*.lf)))
 (preprocess
  (pps ppx_expect)))

(executable
 (name mcpts_lf)
 (public_name mcpts_lf)
 (modules Mcpts_lf)
 (libraries McptsLib_LF))

(env
 (dev
  (flags
   (:standard -w -67 -w -32 -w -33 -w -39))))

(ocamllex Lexer)

(documentation)
